@Library('shared-lib') _

pipeline {
    agent any

    environment {
        IMAGE_NAME = "mohamedtaha934/jenkins_app"
        IMAGE_TAG  = "${BUILD_NUMBER}"
    }

    stages {

        stage('RunUnitTest') {
            steps {
                dir('Jenkins/lab23') {
                    runUnitTest()
                }
            }
        }

        stage('BuildApp') {
            steps {
                dir('Jenkins/lab23') {
                    buildApp()
                }
            }
        }

        stage('BuildImage') {
            steps {
                dir('Jenkins/lab23') {
                    buildImage(IMAGE_NAME, IMAGE_TAG)
                }
            }
        }

        stage('ScanImage') {
            steps {
                dir('Jenkins/lab23') {
                    scanImage(IMAGE_NAME, IMAGE_TAG)
                }
            }
        }
/*
        stage('PushImage') {
            steps {
                dir('Jenkins/lab23') {
                    pushImage(IMAGE_NAME, IMAGE_TAG)
                }
            }
        }

        stage('RemoveImageLocally') {
            steps {
                dir('Jenkins/lab23') {
                    removeImage(IMAGE_NAME, IMAGE_TAG)
                }
            }
        }
*/
        stage('DeployOnK8s') {
            steps {
                dir('Jenkins/lab23') {
                    deployOnK8s('./deployment.yaml')
                }
            }
        }
    }
}
